#ifndef LIMITERS_H_
#define LIMITERS_H_

#define MAX_CHARACTERS_IN_ARRAY 50
#define MAX_FILE_NAME_SIZE 20
#define MAX_LINE_LENGTH 512
#define MAX_STRING_SIZE 255 
#define MAX_NUMBER_OF_STUDENTS 1000000

#endif